version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend/reactapp:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - services_network
    ports:
      - 3000:3000

networks:
  services_network:
